### ISSUE TITLE
Fix  generation::tests::can_generate_from_remote_repo  test in travis (linux)

### ISSUE THREAD

**Issue by Keats** [Keats/kickstart#18]
For some reason it fails to clone the repository:

```
thread 'generation::tests::can_generate_from_remote_repo' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Git { err: Os { code: 2, kind: NotFound, message: "No such file or directory" } })', libcore/result.rs:945:5
```

I tried running the command manually in travis and it worked fine so not too sure what's happening. It also works fine on my machine and on Mac/Windows CI.

**Comment by IvanDelsinne** [comment]
Would running tests in a docker work to reproduce tests ?

If my memory's correct, Travis is running tests inside a docker instance, so making a Dockerfile to run them may be a good reproducing environment.

**Comment by Keats** [comment]
It could help yes. The weird thing is I have other projects with tests writing in temp folder on travis with no issues whatsoever so I'm not sure where it's coming from

**Comment by IvanDelsinne** [comment]
BTW, I may be mistaken, but your `.travis-ci.yml` contains a secret. Just fyi

**Comment by Keats** [comment]
It does, but it's an encrypted one ;)

**Comment by IvanDelsinne** [comment]
better safe than sorry anyways

**Comment by Keats** [comment]
That's fixed in the v1 branch

**Comment by Keats** [comment]
And it's back on travis

**Comment by Keats** [comment]
The issue is likely some permission issue on the tmp dir on travis
