### ISSUE TITLE
To be able to set a "base repository user" for fast cloning

### ISSUE THREAD

**Issue by IvanDelsinne** [Keats/kickstart#19]
*Feature request*

Basically, I'm setting up a common base path for my kickstart templates (something like `https://git.artemix.org/Templates/`), and I'd want to be able to quickly clone a template by simply specifying its name (like `APIBackend` would then resolve to `https://git.artemix.org/Templates/APIBackend`).

The resolution matching logic would be:

- Is it available in a subfolder of kickstart ?
- Is it available under my default base path, if set ?

**Comment by Keats** [comment]
How would the path be set?
The closest thing in cookiecutter are abbreviations in a config file: https://cookiecutter.readthedocs.io/en/latest/advanced/user_config.html

You can define path so you could define `art = https://git.artemix.org/Templates/` and do `kickstart art:some-template`

I'm a bit hesitant with having a base path as it seems to be a very unique usecase

**Comment by IvanDelsinne** [comment]
I didn't think about a prefix, but more of a global setting, but this is an interesting idea that'd allow differenciation between local folder and remote configuration.

A prefix like the cookiecutter's example you shown would be perfect, I couldn't find any mention to it in the README though, is that already implemented or more of a todo ?

If yes, I think the prefix idea would be much nicer than my first "global" idea.

**Comment by Keats** [comment]
Not implemented at all currently, I'm trying to have as little features as possible to start with to avoid feature bloating.

Git also has that prefixes so it's not uniquegit, here's a piece of my `.gitconfig`:

```
[url "https://github.com/"]
    insteadOf = gh:

[url "https://bitbucket.org/"]
    insteadOf = bb:
```

and then you can do `git clone gh:keats/kickstart` for example. Right now kickstart looks for http{s}/git only to determine whether it's a local or a git remote but it could be changed to detect more cases like those prefixes. This way, it would work transparently without the need for a config file since `kickstart` just gives the remote to `git`

**Comment by IvanDelsinne** [comment]
Understood for the part about feature bloating, I acknowledge that it's not a priority.

I didn't know about the Git configuration prefix, that's a nice feature, I'll dig into that.

If you're okay with this, I may try to work on the implementation of a shortcut pattern, both for kickstart to have it and to work into rust.

**Comment by Keats** [comment]
Go for it and let me know if you need help. The code to modify is https://github.com/Keats/kickstart/blob/master/src/utils.rs#L48-L55

**Comment by IvanDelsinne** [comment]
Now, I'm stuck on something: a "global" configuration file.

I don't really know how to load a toml file, handilng paths without any platform-dependence.

My guess would be something like:

- In `~/.config/kickstart.toml`
- In `~/.kickstart.toml`
- In `/etc/kickstart.toml`
- Alongside the kickstart binary

Another solution would be to use [the XDG standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), but is that wise and acceptable to add a crate to handle that ?

**Comment by Keats** [comment]
You don't need a config file since we just shell it to git. People will
modify their `.gitconfig` and that will work automatically

**Comment by IvanDelsinne** [comment]
Okay, I was starting to implement the matching myself, but now I understand what you said.
Gonna work on the real result now.

For confirmation, it's to add a prefix detection on "when it's `^(\d)+:`, it's git", amirite ?

**Comment by Keats** [comment]
> For confirmation, it's to add a prefix detection on "when it's ^(\d)+:, it's git", amirite ?

Seems like it would work fine yeah

**Comment by IvanDelsinne** [comment]
Closed, as it've been merged.
