### ISSUE TITLE
[meta] How is the kickstart release flow?

### ISSUE THREAD

**Issue by Arteneko** [Keats/kickstart#28]
This isn't an issue but more of a general question regarding how kickstart handles its releases.

I have a rust-based project and would like to be able to provide binaries for *at least* windows, linux, and macos.

The thing is, I don't really know how to structure and set up auto-build / auto-release / auto-assets-deployment on the release page.

Do you have a document, or would you accept to write a small paper on your setup?

**Comment by Keats** [comment]
This is actually something I'm experimenting with in https://github.com/Keats/kickstart/pull/27 to use GH actions instead of appveyor/travis. It's not working yet but I'll make a blog post/template when it is.

The current setup is the same as this template: https://github.com/Keats/rust-cli-template

**Comment by Arteneko** [comment]
Thanks for the heads-up.

When you publish it, could you mention me somewhere?

Thanks

**Comment by Keats** [comment]
I'll ping you on this issue.

Any thoughts on https://github.com/Keats/kickstart/issues/24#issuecomment-560147494 ?
I still need to see how exactly cookiecutter handles that.

**Comment by Keats** [comment]
well looks like the GH actions suck for release! I think I'll have to go back to travis/appveyor

**Comment by Arteneko** [comment]
That sucks... which issues did you encounter while trying to work with GH actions?

**Comment by Keats** [comment]
It seems you can only upload one asset. In kickstart case, we want to upload linux/windows/osx builds and that seems to break. It's also missing basic CI stuff, maybe in a few months it will be good

**Comment by Arteneko** [comment]
I'm gonna steal this travis-ci build for my own project, then ;)

Thanks

**Comment by Keats** [comment]
I've switched to Azure Pipelines in the end. I'm using that for [zola](https://github.com/getzola/zola) and it works well. You can check the azure-pipelines.yml file in master. The only annoying thing with setting it up is the atrocious UI/UX of the azure pipelines interface but you only need 5 minutes to set a project up and then never look at it again.

**Comment by Arteneko** [comment]
Thanks for the feedback.

I already tweaked a bit with Azure DevOps, so I'm kinda familiar with their system.

I tried to set up travis per your configuration, but their system really is weird and confusing, especially with their way of handling secrets, which is just bad imho.

**Comment by Keats** [comment]
And now Azure is buggy with releases >_>

https://github.com/microsoft/azure-pipelines-tasks/issues/11558 
https://github.com/microsoft/azure-pipelines-tasks/issues/9394

**Comment by Arteneko** [comment]
How is Azure now?

Also, since you don't use GH Actions, can you hide the tab, as to avoid any confusion for newcomers?

**Comment by Keats** [comment]
Azure is pretty good once it's setup. You can copy the config in this repo, change the names and it should work as a generic Rust release platform.

> Also, since you don't use GH Actions, can you hide the tab, as to avoid any confusion for newcomers?

Thanks, I just removed it

**Comment by Arteneko** [comment]
Thanks for the heads-up, I'll probably use your configuration then!

Closed imho.

**Comment by Arteneko** [comment]
[Works nicely](https://github.com/Arteneko/sinx/releases/tag/v0.2.1), thanks!
