### ISSUE TITLE
Providing a "slugify" functionality

### ISSUE THREAD

**Issue by Arteneko** [Keats/kickstart#31]
I have [a template](https://gitlab.com/Artemix/services/tree/master/templates/service) where I request two related info.

- A name (i.e. a title)
- A slug (to name the file and resulting URL)

This slug is closely related to the name, and I'd like to be able to have *something* to slugify the name the user entered, and use that resulting value as template value.

This would introduce a change, with a concept of transformations.

I see a few ways this could be done.

## `transforms` inside the `template.toml` file

One way would be, for a given variable (one `[[variables]]`), to be able to provide a new key, whose
format would be expected as a key-value object.

```
[[variables]]
name="project"
default="My super project"
prompt="Name your project!"

[variables.transforms]
project_slug = slugify
```

The resulting object would look like this.

```json
{
	"variables": [
		{
			"name": "project",
			"default": "My super project",
			"prompt": "Name your project",
			"transforms": {
				"project_slug": "slugify"
			}
		}
	]
}
```

## Template variable usage filter application

The second proposal would be to allow a pipe syntax in the placeholder keys,
which would then be ran, and the resulting string would be used.

```
$ ls template/
{{project_name|slugify}}
```

The algorithm here would be pretty simple.

```
transform(fullkey):
	[key, ...methods] = split(fullkey, |)
	result = value_for(key) # original value
	for method in methods do
		result = method(result)
		assert result.length, "${method} returned an empty value, cannot continue"
	end
	return result
```

## End

Of course, every method is built-in, and documented.

What do you think?

**Comment by Keats** [comment]
`|` is not allowed on Windows filenames so the second proposal is not a good solution. I need to think a bit about the first one.

Maybe 1.0 is premature if there are more feature request on the schema, I'll release a <1 version in the meantime and we can discuss improvements.

**Comment by Keats** [comment]
I'm kind of warming up to allowing both `|` and something else like `$$` if you want it to work on Windows for filenames/directories only.

**Comment by Arteneko** [comment]
I guess a "less-common" but more compatible option, such as `$$` (if compatible with every supported OS) would be better than to allow *both*, it provides less confusion around what to use, and will allow for maximum compatibility, as to follow the tool's base goal.

**Comment by Keats** [comment]
The issue is that `|` is the official token for filters in Tera so unless we strip them somehow they would be supported, even if not officially/mentioned in the docs. All the code handling would do is `render(path.replace("$$", "|"))`

**Comment by Keats** [comment]
I think adding `$$` (or anything else that works on every OS) as a solution is good in the end. It's pretty niche to need that anyway, cookiecutter still doesn't have it and they do ok.
Are you interested in making a patch for that?

**Comment by Arteneko** [comment]
Sure enough, making a fork for that, right now!
