### ISSUE TITLE
Scripting inside template configuration

### ISSUE THREAD

**Issue by Arteneko** [Keats/kickstart#39]
Okay, so I think I got the dumbest / most awesome idea, which may totally be not credible at all.

What if kickstart embedded some script interpreter or something along those lines, as to allow script execution in templates?

A use case I'm seeing is to get "today's date" or something like that.

**Comment by Keats** [comment]
> A use case I'm seeing is to get "today's date" or something like that.

https://tera.netlify.com/docs/#now ;)

It's very unlikely to add an interpreter to templates though, usually you don't need that much if you're just generating some project files.

**Comment by Arteneko** [comment]
> https://tera.netlify.com/docs/#now ;)

oooh

> It's very unlikely to add an interpreter to templates though, usually you don't need that much if you're just generating some project files.

That's fair.
