### ISSUE TITLE
Github shorthand issues

### ISSUE THREAD

**Issue by chevdor** [Keats/kickstart#47]
I tested shorthand and subfolder and that looks unhappy:
```
kickstart gh:Keats/kickstart -s examples/super-basic
Tmp dir: "/var/folders/9g/zcrsl3n9135455gx1zb2t6pc0000gn/T/"
Error: The template.toml is missing% 
```

I also tested something simpler:
```
kickstart gh:Keats/kickstart-sample   
Tmp dir: "/var/folders/9g/zcrsl3n9135455gx1zb2t6pc0000gn/T/"
Error: The template.toml is missing%   
```

Using `kickstart https://github.com/Keats/kickstart-sample` does work fine.

**Comment by Keats** [comment]
This is using git shortcuts, do you have them set up in your gitconfig?

**Comment by chevdor** [comment]
I did not know about those so surely not.
Let me check how that works, I will check again and likely close this issue today if everything works fine.

**Comment by Keats** [comment]
You can put something like 

```

[url "https://github.com/"]
    insteadOf = gh:

[url "https://bitbucket.org/"]
    insteadOf = bb:

```
in your `.gitconfig`  but I think it's confusing to have that in the README since it looks like a kickstart native feature... I should probably remove it,.

**Comment by chevdor** [comment]
Yes, indeed, I did think it was from kickstart. You could remove it (simpler) or better just mention that the shorthands must be defined before the next examples can work (https://git-scm.com/docs/git-config/2.15.4#Documentation/git-config.txt-urlltbasegtinsteadOf)

**Comment by chevdor** [comment]
Closing, it works fine indeed, once the shorthands are set.
