### ISSUE TITLE
--sub-dir erroneously report a missing template.toml

### ISSUE THREAD

**Issue by chevdor** [Keats/kickstart#52]
Trying to escape #51, I tested to see if the `--sub-dir` could help.

I tested a very basic template and the following works:
```
kickstart . -o /tmp   
```

Using `--subdir` however never worked although I provide a sub dir of the template
```
kickstart . --sub-dir .github  -o /tmp   
```

The error is:
```
Error: The template.toml is missing%                                                                                                             
```

We know the template is not missing and valid since the first test did work fine.

**Comment by Keats** [comment]
See the original PR: https://github.com/Keats/kickstart/pull/23

it's meant to be used when you have multiple templates in a directory so the subdir needs to be a template itself. It needs to be documented though.

**Comment by chevdor** [comment]
I see, I did not expect this requirement indeed.
