### ISSUE TITLE
Error: File name too long (os error 36): ""

### ISSUE THREAD

**Issue by sacha-l** [Keats/kickstart#54]
I get this error when using:
```bash
 kickstart . -o new-project-folder
```
Then it creates a folder with seemingly infinite sub directories of the same name &mdash; all empty.

 This could be something specific to how the ```-o``` command is implemented. Have you come across this issue @Keats ?
Thanks!

**Comment by Keats** [comment]
I haven't seen that but that sounds like a bug. Do you have an easy reproduction repo somewhere?

**Comment by sacha-l** [comment]
Yes, I'm working on this project [here](https://github.com/sacha-l/kickstart-substrate). To reproduce you probably will need to clone the repo first and them run:
```bash
kickstart . -o proj-name
```
The: `kickstart https://github.com/sacha-l/kickstart-substrate` command seems to be having issues with reading the submodule.

**Comment by Keats** [comment]
> command seems to be having issues with reading the submodule.

The `git clone` was not including the submodules, should be fixed in the next version.
The other issue was that the output dir was not being ignored while generating, resulting in that non-stop recursion.

Can you try https://github.com/Keats/kickstart/pull/53 ?

**Comment by sacha-l** [comment]
Great, that worked!

**Comment by Keats** [comment]
cool I'll release it soon then
