### ISSUE TITLE
Template trigering on ${{ foo.bar }}

### ISSUE THREAD

**Issue by chevdor** [Keats/kickstart#55]
I am testing a template that scaffold a project that happens to contain some github actions.
So there is a `.github/workflows/foo.yml` file. There is current no templating defined in this file so it should be treated as simple text.
However, kickstart hits some github actions variables defined as `${{ foo.bar }}` and tera/kickstart complains about those "missing" `foo.bar` variables.

Would it be possible for the Tera to NOT trigger on `${{ }}` ?
Or could I escape the template to prevent this issue ?

Today, my workaround is to use the `ignore` config and skip the whole folder but this is rather unconvenient.

**Comment by chevdor** [comment]
I guess I could rephrase into a question:
How could I have a file that will **render** as `${{ foo.bar  }}` without Tera thinking it should replace ffo.bar in there.

**Comment by Keats** [comment]
You can use `{% raw %}${{ foo.bar }}{% endraw %}`

**Comment by chevdor** [comment]
That works for me, closing.
