### ISSUE TITLE
Run some commands after the templating ends.

### ISSUE THREAD

**Issue by elenakrittik** [Keats/kickstart#63]
E.g. my template requires the project to be a git repository, but bundling a `.git` folder is, well, meh.
It would be great if there was a way to run, e.g., `git init` after the project initializes. Understandably, this is totally insecure, so i propose instead a way to just print some text out when
templating ends so one could print "This template requires your project to be a Git repository. Run `git init` to initialize one." and then the user will decide for themselves whether stuff said in the output
is safe to do. (A warning that the output is not coming from kickstart itself would be appropriate too i think.)

**Comment by Keats** [comment]
I think adding some end state messaging is a good idea. We probably want to be able to have multiple depending on some answers during the generation

**Comment by Keats** [comment]
Hooks are available in 0.5.0
