### ISSUE TITLE
regression build failure with 0.5.0 release

### ISSUE THREAD

**Issue by chenrui333** [Keats/kickstart#72]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error test log</summary>

```
  ==> /home/linuxbrew/.linuxbrew/Cellar/kickstart/0.5.0/bin/kickstart --no-input /tmp/kickstart-test-20241213-9939-1ebzi9
  error: the following required arguments were not provided:
    --output-dir <OUTPUT_DIR>
  
  Usage: kickstart --output-dir <OUTPUT_DIR> --no-input <TEMPLATE>
  
  For more information, try '--help'.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/12322830068/job/34397415478?pr=201086
relates to Homebrew/homebrew-core#201086

---

I tried to update to use `system bin/"kickstart", "--no-input", testpath.to_s, "--output-dir", testpath.to_s` which is `/opt/homebrew/Cellar/kickstart/0.5.0/bin/kickstart --no-input /private/tmp/kickstart-test-20241213-55408-34xy6i --output-dir /private/tmp/kickstart-test-20241213-55408-34xy6i`, but  still not see it is working.

```
/private/tmp/kickstart-test-20241213-55408-34xy6i
├── template.toml
└── {{file_name}}.txt
```

would appreciate some pointer.

**Comment by Keats** [comment]
Oh I think it's because it's using the same output directory as the input one. It should probably error in that case

**Comment by chenrui333** [comment]
@Keats should I use diff directories for template and files?

**Comment by Keats** [comment]
You should use an output directory different from the input directory yes

**Comment by chenrui333** [comment]
that works, thanks!
